### ISSUE TITLE
使用后报错。大神求原因

### ISSUE THREAD

**Issue by ximencx** [shichaohui/PageRecyelerViewDemo#1]
- `: FATAL EXCEPTION: main
                                                                           Process: com.apicloud.A6984334434180, PID: 18968
                                                                           java.lang.IndexOutOfBoundsException: Invalid item position 0(0). Item count:0
                                                                               at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4622)
                                                                               at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4617)
                                                                               at com.apicloud.A6984334434180.view.PageRecycle.AutoGridLayoutManager.onMeasure(AutoGridLayoutManager.java:39)
                                                                               at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2614)
                                                                               at com.apicloud.A6984334434180.view.PageRecycle.PageRecyclerView.onMeasure(PageRecyclerView.java:101)
                                                                               at android.view.View.measure(View.java:17430)
                                                                               at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:727)
                                                                               at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:463)
                                                                               at android.view.View.measure(View.java:17430)
                                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
                                                                               at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                               at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                               at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                               at android.view.View.measure(View.java:17430)
                                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
                                                                               at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
                                                                               at android.view.View.measure(View.java:17430)
                                                                               at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:727)
                                                                               at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:463)
                                                                               at android.view.View.measure(View.java:17430)
                                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
                                                                               at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
                                                                               at android.view.View.measure(View.java:17430)
                                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
                                                                               at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                               at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                               at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                               at android.view.View.measure(View.java:17430)
                                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
                                                                               at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
                                                                               at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2560)
                                                                               at android.view.View.measure(View.java:17430)
                                                                               at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2001)
                                                                               at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1166)
                                                                               at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1372)
                                                                               at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
                                                                               at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
                                                                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                               at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                               at android.view.Choreographer.doFrame(Choreographer.java:550)
                                                                               at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:135)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
  `
  本人邮箱：454366460@qq.com

**Comment by idealgn** [comment]
我的错误和上面的错误一样,不知道楼主怎么解决的,麻烦告知

**Comment by ximencx** [comment]
@idealcn 我都放弃治疗了  这个issue很早的了

**Comment by shichaohui** [comment]
这个 Demo 是刚学 RecyclerView 的时候的一个练手项目，存在很多问题，解决方案也不是很好。最近手头有个类似的需求，正在使用 RecyclerView + GridLayout + SnapHelper 作为解决方案，你们有兴趣也可以自己动手实现一下。

**Comment by idealgn** [comment]
大神写好的话,麻烦再给我发个留言可好,非常感谢

**Comment by ximencx** [comment]
@idealcn 自己写啊
